### ISSUE TITLE
Nightly build - chain sync benchmarking

### ISSUE THREAD

**Issue by oneEdoubleD** [input-output-hk/cardano-ops#11]
We would like to benchmark chain syncing on cardano-node. This would involve launching a node, built from the Master branch, with a certain logging configuration for a certain period of time (1 hour to begin with). We'd like to aggregate the log files and use these to evaluate the nodes performance over a period of time. 

The steps I'm currently taking to set up logging are as follows. 

**Steps to set up the modified log configuration**

1. Save this as `log-configuration.yaml` in a directory `launch_mainnet.d` in the root of the `cardano-node` repo
```
# global filter; messages must have at least this severity to pass:
minSeverity: Debug
​
# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  1000
  rpMaxAgeHours:   24
​
# these backends are initialized:
setupBackends:
  - AggregationBK
  - KatipBK
  - EKGViewBK
  #- EditorBK
​
# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK
​
# if wanted, the GUI is listening on this port:
#hasGUI: 13787
​
# if wanted, the EKG interface is listening on this port:
hasEKG: 13788
​
# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: FileSK
    scName: "node.log"
    scFormat: ScText
    scRotation: null
  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText
​
# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - FileSK
    - "node.log"
  - - StdoutSK
    - stdout
​
# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
  mapSubtrace:
    benchmark:
      contents:
        - GhcRtsStats
        - MonotonicClock
      subtrace: ObservableTrace
    '#ekgview':
      contents:
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: .monoclock.basic.
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.cpuNs.timed.
      - - tag: StartsWith
          contents: '#ekgview.#aggregation.cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.gcNum.timed.
      subtrace: FilterTrace
    'cardano.epoch-validation.utxo-stats':
      # Change the `subtrace` value to `Neutral` in order to log
      # `UTxO`-related messages during epoch validation.
      subtrace: NoTrace
    '#messagecounters.aggregation':
      subtrace: NoTrace
    '#messagecounters.ekgview':
      subtrace: NoTrace
    '#messagecounters.switchboard':
      subtrace: Neutral
  mapBackends:
    cardano.epoch-validation.benchmark:
      - AggregationBK
    '#aggregation.cardano.epoch-validation.benchmark':
      - EKGViewBK
```

2. Build the node with `nix-build -A scripts.mainnet.node -o launch_mainnet`

3. Adjust `launch_mainnet` with something like this: 
```
#!/nix/store/vlb7kcc1k035vpyrgsj9kk7380yh68wd-bash-4.4-p23/bin/bash
set -euo pipefail
​
BASEDIR=`pwd`
​
mkdir -p "state-node-mainnet"
cd "state-node-mainnet"
NODE=/nix/store/mgpca090rchy69s42r1wh2xz3cs96sfi-cardano-node-exes/bin/cardano-node
NODE="cabal new-run exe:cardano-node -- "
exec ${NODE} \
  --genesis-file /nix/store/qd60rqsk0rjdrckg2js8dgl9jh21bd1j-mainnet-genesis.json \
  --genesis-hash 5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb \
  --log-config ${BASEDIR}/launch_mainnet.d/log-configuration.yaml \
  --database-path .//db-mainnet \
  node \
  --topology /nix/store/g8fb0sjaq39dbxnvv35dqcwafgvc26vx-topology.yaml \
  --real-pbft \
  --node-id 0 \
  --host-addr 127.0.0.1 \
  --port 3001 \
  --socket-path socket/node-core-0.socket \
   \
```
Note `log-config` is using `log-configuration.yaml` that we set up in [1]. 

4. Run this command to generate a csv from the log files
```
sed -ne 's/.*\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [.:0-9]\+\) .*{"event":{"kind":"TraceCopyToImmDBEvent.CopiedBlockToImmDB","slot":{"kind":"Tip","tip":".*@\([0-9]\+\)".*/\1 \2/p;' ./node-* > $(date +%F_%T).csv
```
